"""split name

Revision ID: 300d66242fdd
Revises: 36d1ebe0a3b1
Create Date: 2026-03-22 12:32:20.388895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300d66242fdd'
down_revision: Union[str, Sequence[str], None] = '36d1ebe0a3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('contact', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('contact', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contact', 'last_name')
    op.drop_column('contact', 'first_name')
    # ### end Alembic commands ###
