"""add email_capture table

Revision ID: 923963de68a2
Revises: 300d66242fdd
Create Date: 2026-04-11 11:09:12.803096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923963de68a2'
down_revision: Union[str, Sequence[str], None] = '300d66242fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_capture',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_capture_email'), 'email_capture', ['email'], unique=False)
    op.create_index(op.f('ix_email_capture_resource'), 'email_capture', ['resource'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_capture_resource'), table_name='email_capture')
    op.drop_index(op.f('ix_email_capture_email'), table_name='email_capture')
    op.drop_table('email_capture')
    # ### end Alembic commands ###
